In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
import math


data= pd.read_csv(r"C:\Users\HOLLARMYDE {ALEXIX}\Downloads\energydata_complete.csv")

In [11]:
data

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [13]:
data.shape

(19735, 29)

In [2]:
X = data['T2'].values.reshape(-1, 1)
y = data['T6'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
                                                    
l_model = LinearRegression()
l_model.fit(X_train, y_train)

y_pred = l_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)

print(f"RMSE: {rmse:.3f}")

RMSE: 3.651

In [3]:
data = data.drop(["date", "lights"], axis=1)
X = data.drop("Appliances", axis=1)
y = data["Appliances"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
l_model = LinearRegression()
l_model.fit(X_train_scaled, y_train)
y_train_pred = l_model.predict(X_train_scaled)
mae_train = mean_absolute_error(y_train, y_train_pred)

print(f"Mean Absolute Error (Training Set): {mae_train:.3f}")

Mean Absolute Error (Training Set): 53.121

In [4]:
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = (mse_train ** 0.5)

print(f"Root Mean Squared Error (Training Set): {rmse_train:.3f}")

Root Mean Squared Error (Training Set): 94.882

In [5]:
y_test_pred = l_model.predict(X_test_scaled)
mae_test = mean_absolute_error(y_test, y_test_pred)
print(f"Mean Absolute Error (Test Set): {mae_test:.3f}")

Mean Absolute Error (Test Set): 53.583

In [6]:
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = (mse_test ** 0.5)
print(f"Root Mean Squared Error (Test Set): {rmse_test:.3f}")

Root Mean Squared Error (Test Set): 94.411

In [7]:
lasso_model = Lasso()
lasso_model.fit(X_train_scaled, y_train)
feature_weights = lasso_model.coef_
non_zero_feature_count = sum(feature_weights != 0)
print(f"Number of features with non-zero feature weights: {non_zero_feature_count}")

Number of features with non-zero feature weights: 4

In [8]:
lasso_y_test_pred = lasso_model.predict(X_test_scaled)
lasso_mse_test = mean_squared_error(y_test, lasso_y_test_pred)
lasso_rmse_test = (lasso_mse_test ** 0.5)
print(f"RMSE with Lasso Regression (Test Set): {lasso_rmse_test:.3f}")

RMSE with Lasso Regression (Test Set): 100.790

In [9]:
y_train_pred = l_model.predict(X_train_scaled)
y_test_pred = l_model.predict(X_test_scaled)
mse_train = mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_train = (mse_train ** 0.5)
rmse_test = (mse_test ** 0.5)
print(f"RMSE on Training Set: {rmse_train:.3f}")
print(f"RMSE on Test Set: {rmse_test:.3f}")
if rmse_train < rmse_test:
    print("The model may be overfitting to the training set.")
else:
    print("The model is not showing significant signs of overfitting.")

RMSE on Training Set: 94.882
RMSE on Test Set: 94.411
The model is not showing significant signs of overfitting.

In [10]:
r_model = Ridge()
r_model.fit(X_train_scaled, y_train)
from sklearn.metrics import mean_squared_error
ridge_y_test_pred = r_model.predict(X_test_scaled)
ridge_mse_test = mean_squared_error(y_test, ridge_y_test_pred)
ridge_rmse_test = (ridge_mse_test ** 0.5)
print(f"RMSE with Ridge Regression on Test Set: {ridge_rmse_test:.3f}")
original_rmse_test = rmse_test
print(f"RMSE with Original Linear Regression on Test Set: {original_rmse_test:.3f}")
if ridge_rmse_test == original_rmse_test:
    print("The RMSE values are the same for both models.")
elif ridge_rmse_test < original_rmse_test:
    print("The RMSE is lower with the Ridge regression model, indicating potential improvement.")
else:
    print("The RMSE is higher with the Ridge regression model.")

RMSE with Ridge Regression on Test Set: 94.476
RMSE with Original Linear Regression on Test Set: 94.411
The RMSE is higher with the Ridge regression model.